routes/admin.php
<?php

Route::group(['middleware' => 'web'], function() {

    Route::group(['as' => 'admin.', 'prefix' => 'admin'], function(){

        Route::get('important/constants', 'ApplicationController@list_of_constants');

        Route::get('clear-cache', function() {

            $exitCode = Artisan::call('config:cache');

            return back();

        })->name('clear-cache');

        Route::get('login', 'Auth\AdminLoginController@showLoginForm')->name('login');

        Route::post('login', 'Auth\AdminLoginController@login')->name('login.post');

        Route::get('logout', 'Auth\AdminLoginController@logout')->name('logout');

        /***
         *
         * Admin Account releated routes
         *
         */

        Route::get('profile', 'AdminController@profile')->name('profile');

        Route::post('profile/save', 'AdminController@profile_save')->name('profile.save');

        Route::post('change/password', 'AdminController@change_password')->name('change.password');

        Route::get('/', 'AdminController@index')->name('dashboard');
        
        Route::get('users', 'AdminController@users_index')->name('users.index');

        Route::get('users/create', 'AdminController@users_create')->name('users.create');

        Route::get('users/edit', 'AdminController@users_edit')->name('users.edit');

        Route::post('users/save', 'AdminController@users_save')->name('users.save');

        Route::get('users/view', 'AdminController@users_view')->name('users.view');

        Route::get('users/delete', 'AdminController@users_delete')->name('users.delete');

        Route::get('users/status', 'AdminController@users_status')->name('users.status');

        Route::get('users/verify', 'AdminController@users_verify_status')->name('users.verify');

        Route::get('users/subscriptions','AdminController@users_subscriptions_index')->name('users.subscriptions_index');

        Route::post('users/subscription_payments','AdminController@users_subscription_payments_save')->name('users.subscriptions_payments');

        Route::get('users/subscriptions_payments/delete','AdminController@users_subscription_payments_delete')->name('users.subscriptions_payments_delete');

        Route::post('/users/bulk_action', 'AdminController@users_bulk_action')->name('users.bulk_action');

        //subscriptions
        Route::get('subscriptions', 'AdminController@subscriptions_index')->name('subscriptions.index');

        Route::get('subscriptions/create', 'AdminController@subscriptions_create')->name('subscriptions.create');

        Route::get('subscriptions/edit', 'AdminController@subscriptions_edit')->name('subscriptions.edit');

        Route::post('subscriptions/save', 'AdminController@subscriptions_save')->name('subscriptions.save');

        Route::get('subscriptions/view', 'AdminController@subscriptions_view')->name('subscriptions.view');

        Route::get('subscriptions/delete', 'AdminController@subscriptions_delete')->name('subscriptions.delete');

        Route::get('subscriptions/status', 'AdminController@subscriptions_status')->name('subscriptions.status');

        //Subscription Payments
        Route::get('subscription_payments/index','AdminController@subscription_payments_index')->name('subscription_payments.index');

        Route::get('subscription_payments/view','AdminController@subscription_payments_view')->name('subscription_payments.view');

        Route::get('revenue/dashboard','AdminController@revenue_dashboard')->name('revenue.dashboard');

        //meetings crud
        Route::get('meetings', 'AdminController@meetings_index')->name('meetings.index');

        Route::get('meetings/create', 'AdminController@meetings_create')->name('meetings.create');

        Route::get('meetings/edit', 'AdminController@meetings_edit')->name('meetings.edit');

        Route::post('meetings/save', 'AdminController@meetings_save')->name('meetings.save');

        Route::get('meetings/view', 'AdminController@meetings_view')->name('meetings.view');

        Route::get('meetings/delete', 'AdminController@meetings_delete')->name('meetings.delete');

        Route::get('meetings/status', 'AdminController@meetings_status')->name('meetings.status');

        Route::post('meetings/bulk_action', 'AdminController@meetings_bulk_action')->name('meetings.bulk_action');


        // settings

        Route::get('settings-control', 'AdminController@settings_control')->name('control');

        Route::get('settings', 'AdminController@settings')->name('settings'); 

        Route::post('settings/save', 'AdminController@settings_save')->name('settings.save'); 
        Route::post('env_settings','AdminController@env_settings_save')->name('env-settings.save');

        // STATIC PAGES

        Route::get('/static_pages' , 'AdminController@static_pages_index')->name('static_pages.index');

        Route::get('/static_pages/create', 'AdminController@static_pages_create')->name('static_pages.create');

        Route::get('/static_pages/edit', 'AdminController@static_pages_edit')->name('static_pages.edit');

        Route::post('/static_pages/save', 'AdminController@static_pages_save')->name('static_pages.save');

        Route::get('/static_pages/delete', 'AdminController@static_pages_delete')->name('static_pages.delete');

        Route::get('/static_pages/view', 'AdminController@static_pages_view')->name('static_pages.view');

        Route::get('/static_pages/status', 'AdminController@static_pages_status_change')->name('static_pages.status');

        // SUPPORT CONTACTS

        Route::get('support_contacts' , 'AdminController@support_contacts_index')->name('support_contacts.index');

        Route::get('support_contacts/view', 'AdminController@support_contacts_view')->name('support_contacts.view');


        Route::get('meeting_records', 'AdminController@meeting_records_index')->name('meeting_records.index');

        Route::get('meeting_records/view', 'AdminController@meeting_records_view')->name('meeting_records.view');

        Route::get('meeting_records/delete', 'AdminController@meeting_records_delete')->name('meeting_records.delete');


        Route::post('subscriptions/bulk_action', 'AdminController@subscriptions_bulk_action')->name('subscriptions.bulk_action');

        Route::post('support_contacts/bulk_action', 'AdminController@support_contacts_bulk_action')->name('support_contacts.bulk_action');

    });

});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');

Route::get('/home', 'AdminController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Setting, DB;
use App\Notifications\ResetPassword as ResetPasswordNotification;


class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $appends = [
        'user_id', 'user_unique_id'
    ];

    public function getUserIdAttribute() {

        return $this->id;
    }

    public function getUserUniqueIdAttribute() {

        return $this->unique_id;
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Get the UserCard record associated with the user.
     */
    public function userCards() {
        
        return $this->hasMany(UserCard::class, 'user_id');
    }

    public function getSubscribedusers()
    {
        return $this->hasMany(SubscriptionPayment::class, 'user_id', 'id');
    }

    public function getMeetingUsers() {

        return $this->hasMany(MeetingUser::class, 'user_id');
    }

   
    public static function boot() {

        parent::boot();

        static::creating(function ($model) {

            $model->attributes['first_name'] = $model->attributes['last_name'] = $model->attributes['name'];

            $model->attributes['is_verified'] = USER_EMAIL_VERIFIED;

            if (Setting::get('is_account_email_verification') == YES && envfile('MAIL_USERNAME') && envfile('MAIL_PASSWORD')) { 

                if($model->attributes['login_by'] == 'manual') {

                    $model->generateEmailCode();

                }

            }

            $model->attributes['payment_mode'] = COD;

            $model->attributes['username'] = routefreestring($model->attributes['name']).rand(1,999999);

            $model->attributes['unique_id'] = uniqid();

            $model->attributes['token'] = \Helper::generate_token();

            $model->attributes['token_expiry'] = \Helper::generate_token_expiry();

            $model->attributes['status'] = USER_APPROVED;

            if(in_array($model->attributes['login_by'], ['facebook', 'google', 'apple', 'linkedin', 'instagram'] )) {
                
                $model->attributes['password'] = \Hash::make($model->attributes['social_unique_id']);
            }

        });

        static::created(function($model) {

            $model->attributes['email_notification_status'] = $model->attributes['push_notification_status'] = YES;

            $model->attributes['unique_id'] = "UID"."-".$model->attributes['id']."-".uniqid();

            $model->save();
        
        });

        static::updating(function($model) {

            $model->attributes['username'] = routefreestring($model->attributes['name']).rand(1,999999);

            $model->attributes['first_name'] = $model->attributes['last_name'] = $model->attributes['name'];

        });

        static::deleting(function ($model){

            \Helper::delete_file($model->picture , PROFILE_PATH_USER);

            $model->userCards()->delete();

            $model->Meeting()->delete();

            $model->SubscriptionPayment()->delete();

            $model->SupportContact()->delete();

            $model->meetingUsers()->delete();

            $model->meetingRecord()->delete();

        });

    }


    /**
     * Get the meetings record associated with the user.
     */
    public function Meeting() {
        
        return $this->hasMany(Meeting::class, 'user_id');
    }

    public function meetingRecord() {
        
        return $this->hasMany(MeetingRecord::class, 'user_id');
    }

    public function SubscriptionPayment() {
        
        return $this->hasMany(SubscriptionPayment::class, 'user_id');
    }

    public function SupportContact() {
        
        return $this->hasMany(SupportContact::class, 'user_id');
    }

    public function meetingUsers() {

        return $this->hasMany(MeetingUser::class,'user_id');
    }

    /**
     * Generates Token and Token Expiry
     * 
     * @return bool returns true if successful. false on failure.
     */

    protected function generateEmailCode() {

        $this->attributes['verification_code'] = \Helper::generate_email_code();

        $this->attributes['verification_code_expiry'] = \Helper::generate_email_expiry();

        // Check Email verification controls and email configurations

        if(Setting::get('is_account_email_verification') == YES && Setting::get('is_email_notification') == YES && Setting::get('is_email_configured') == YES) {

            if($model->attributes['login_by'] != 'manual') {

                $this->attributes['is_verified'] = USER_EMAIL_VERIFIED;

            } else {

                $this->attributes['is_verified'] = USER_EMAIL_NOT_VERIFIED;
            }

        } else { 

            $this->attributes['is_verified'] = USER_EMAIL_VERIFIED;
        }

        return true;
    
    }

}

resources/views/admin/users/_form.blade.php
<div class="row">

    <div class="col-12">

        <div class="card">

            <div class="card-body">

                <div class="border-bottom pb-3">

                    <h5 class="text-uppercase">{{$user_details->id ? tr('edit_user') : tr('add_user')}}

                        <a class="btn btn-outline-primary float-right" href="{{route('admin.users.index')}}">
                            <i class="fa fa-plus"></i> {{tr('view_users')}}
                        </a>
                  
                    </h5>

                </div>

                <form class="forms-sample pt-3" action="{{ Setting::get('is_demo_control_enabled') == NO ? route('admin.users.save') : '#'}}" method="POST" enctype="multipart/form-data" role="form">
                    @csrf

                   
                    @if($user_details->id)

                    <input type="hidden" name="user_id" id="user_id" value="{{$user_details->id}}" />

                    @endif

                    <input type="hidden" name="login_by" id="login_by" value="{{$user_details->login_by ?: 'manual'}}" />

                    <div class="row">
                        <div class="form-group col-md-6">
                            <label for="name">{{ tr('name') }} <span class="admin-required">*</span> </label>
                            <input type="text" class="form-control" id="name" name="name" placeholder="{{ tr('name') }}" value="{{ old('name') ?: $user_details->name}}" required />
                        </div>

                        <div class="form-group col-md-6">
                            <label for="mobile">{{ tr('mobile') }} </label>

                            <input type="number"  minlength="10" maxlength="12" class="form-control" pattern="[0-9]{6,13}" id="mobile" name="mobile" placeholder="{{ tr('mobile') }}" value="{{ old('mobile') ?: $user_details->mobile}}"/>
                        </div>
                    </div>

                    <div class="row">
                        <div class="form-group col-md-6">
                            <label for="email">{{ tr('email')}} <span class="admin-required">*</span></label>
                            <input type="email"  class="form-control" id="email" name="email" placeholder="{{ tr('email')}}" value="{{ old('email') ?: $user_details->email}}" required 
                            
                            />
                        </div>

                        @if(!$user_details->id)

                        <div class="form-group col-md-6">
                            <label for="password">{{ tr('password') }} <span class="admin-required">*</span></label>
                            <input type="password" class="form-control" id="password" name="password" placeholder="{{ tr('password') }}" value="{{old('password')}}" required title="{{ tr('password_notes') }}" />
                        </div>

                        @endif
                    </div>

                    <div class="row">
                        <div class="form-group col-md-6">
                            <label>{{tr('upload_image')}}</label>

                            <div class="input-group col-xs-12">
                                <input type="file" class="form-control file-upload-info" name="picture" placeholder="{{tr('upload_image')}}" accept="image/*" />

                                <div class="input-group-append">
                                    <button class="btn btn-info" type="button">{{tr('upload')}}</button>
                                </div>
                            </div>
                        </div>
                    </div>
                   
                    <button type="reset" class="btn btn-warning">{{ tr('reset')}}</button>

                    @if(Setting::get('is_demo_control_enabled') == NO )

                    <button type="submit" class="btn btn-success mr-2">{{ tr('submit') }}</button>

                    @else

                    <button type="button" class="btn btn-success mr-2" disabled>{{ tr('submit') }}</button>

                    @endif
                   
                </form>

            </div>

        </div>

    </div>

</div>

resources/views/admin/users/create.blade.php
@extends('layouts.admin') 

@section('content-header', tr('users'))

@section('bread-crumb')

    <li class="breadcrumb-item">
    	<a href="{{ route('admin.users.index') }}">{{tr('users')}}</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
    	<span>{{tr('add_user')}}</span>
    </li>
           
@endsection 

@section('content') 

	@include('admin.users._form') 

@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.admin')

@section('content-header', tr('users'))

@section('bread-crumb')

    <li class="breadcrumb-item"><a href="{{ route('admin.users.index') }}">{{tr('users')}}</a></li>
    
    <li class="breadcrumb-item active" aria-current="page">
    	<span>{{ tr('edit_user') }}</span>
    </li>
           
@endsection 

@section('content')

	@include('admin.users._form')

@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('content-header', tr('users'))

@section('bread-crumb')

<li class="breadcrumb-item"><a href="{{ route('admin.users.index')}}">{{tr('users')}}</a></li>

<li class="breadcrumb-item active" aria-current="page">
    <span>{{ tr('view_users') }}</span>
</li>

@endsection

@section('content')

<div class="row">

    <div class="col-12">

        <div class="card">

            <div class="card-body">

                <div class="border-bottom pb-3">


                    <h5 class="text-uppercase">{{tr('view_users')}}

                        <a class="btn btn-outline-primary float-right user_add" href="{{route('admin.users.create')}}">
                            <i class="fa fa-plus"></i> {{tr('add_user')}}
                        </a>

                        <div class="dropdown float-right">
                            <button class="btn btn-outline-primary  dropdown-toggle float-right bulk-action-dropdown text-uppercase" href="#" id="dropdownMenuOutlineButton2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-plus"></i> {{tr('bulk_action')}}
                            </button>

                            <div class="dropdown-menu float-right" aria-labelledby="dropdownMenuOutlineButton2">

                                <a class="dropdown-item action_list" href="#" id="bulk_delete">
                                    {{tr('delete')}}
                                </a>

                                <a class="dropdown-item action_list" href="#" id="bulk_approve">
                                    {{ tr('approve') }}
                                </a>

                                <a class="dropdown-item action_list" href="#" id="bulk_decline">
                                    {{ tr('decline') }}
                                </a>
                            </div>
                        </div>

                        <div class="bulk_action">

                            <form action="{{route('admin.users.bulk_action')}}" id="users_form" method="POST" role="search">

                                @csrf

                                <input type="hidden" name="action_name" id="action" value="">

                                <input type="hidden" name="selected_users" id="selected_ids" value="">

                                <input type="hidden" name="page_id" id="page_id" value="{{ (request()->page) ? request()->page : '1' }}">

                            </form>

                        </div>


                    </h5>


                </div>

                @include('admin.users._search')

                <table id="basic-datatable" class="table dt-responsive nowrap">

                    <thead>
                        <tr>
                            <th>
                                <input id="check_all" type="checkbox" class="chk-box-left">
                            </th>
                            <th>{{tr('s_no')}}</th>
                            <th>{{tr('name')}}</th>
                            <th>{{tr('email')}}</th>
                            <th>{{tr('mobile')}}</th>
                            <th>{{tr('status')}}</th>
                            <th>{{tr('verify')}}</th>
                            <th>{{tr('action')}}</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($users as $i => $user_details)

                        <tr>
                            <td id="check{{$user_details->id}}"><input type="checkbox" name="row_check" class="faChkRnd chk-box-inner-left" id="{{$user_details->id}}" value="{{$user_details->id}}"></td>

                            <td>{{$i+$users->firstItem()}}</td>

                            <td>
                                <a href="{{route('admin.users.view' , ['user_id' => $user_details->id])}}"> {{ $user_details->name }}
                                </a>
                            </td>

                            <td> {{ $user_details->email }} </td>

                            <td> {{ ($user_details->mobile > 1) ? $user_details->mobile : tr('unavailable')}} </td>

                            <td>

                                @if($user_details->status == USER_APPROVED)

                                <span class="badge badge-success">{{ tr('approved') }} </span>

                                @else

                                <span class="badge badge-danger">{{ tr('declined') }} </span>

                                @endif

                            </td>

                            <td>

                                @if($user_details->is_verified == USER_EMAIL_VERIFIED)

                                <span class="badge badge-success">{{ tr('verified') }} </span>

                                @else

                                <a class="badge badge-info" href="{{ route('admin.users.verify', ['user_id' => $user_details->id]) }}">
                                    {{ tr('verify') }}
                                </a>

                                @endif

                            </td>

                            <td>

                                <div class="template-demo">

                                    <div class="dropdown">

                                        <button class="btn btn-outline-primary  dropdown-toggle" type="button" id="dropdownMenuOutlineButton1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            {{tr('action')}}
                                        </button>

                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuOutlineButton1">

                                            <a class="dropdown-item" href="{{ route('admin.users.view', ['user_id' => $user_details->id]) }}">
                                                {{tr('view')}}
                                            </a>

                                            @if(Setting::get('is_demo_control_enabled') == NO)
                                            <a class="dropdown-item" href="{{ route('admin.users.edit', ['user_id' => $user_details->id]) }}">
                                                {{tr('edit')}}
                                            </a>

                                            <a class="dropdown-item" href="{{route('admin.users.delete', ['user_id' => $user_details->id,'page'=>request()->input('page')])}}" onclick="return confirm(&quot;{{tr('user_delete_confirmation' , $user_details->name)}}&quot;);">
                                                {{tr('delete')}}
                                            </a>
                                            @else

                                            <a class="dropdown-item text-muted" href="javascript:;">{{tr('edit')}}</a>

                                            <a class="dropdown-item text-muted" href="javascript:;">{{tr('delete')}}</a>
                                            @endif

                                            <div class="dropdown-divider"></div>

                                            @if($user_details->is_verified == USER_EMAIL_NOT_VERIFIED)

                                            <a class="dropdown-item" href="{{ route('admin.users.verify', ['user_id' => $user_details->id]) }}"> {{ tr('verify') }}
                                            </a>

                                            @endif

                                            @if($user_details->status == USER_APPROVED)

                                            <a class="dropdown-item" href="{{ route('admin.users.status', ['user_id' => $user_details->id]) }}" onclick="return confirm(&quot;{{$user_details->first_name}} - {{tr('user_decline_confirmation')}}&quot;);">
                                                {{ tr('decline') }}
                                            </a>

                                            @else

                                            <a class="dropdown-item" href="{{ route('admin.users.status', ['user_id' => $user_details->id]) }}">
                                                {{ tr('approve') }}
                                            </a>

                                            @endif

                                            @if($user_details->is_verified == USER_EMAIL_VERIFIED)

                                            <a class="dropdown-item" href="{{ route('admin.users.verify',['user_id' => $user_details->id] ) }}">
                                                {{ tr('unverify') }}
                                            </a>
                                            @else

                                            <a class="dropdown-item" href="{{ route('admin.users.verify',['user_id' => $user_details->id] ) }}">
                                                {{ tr('verify') }}
                                            </a>

                                            @endif

                                            <a class="dropdown-item" href="{{route('admin.users.subscriptions_index',['user_id' => $user_details->id])}}">{{tr('subscriptions')}}</a>

                                            <a class="dropdown-item" href="{{route('admin.meetings.index',['user_id' => $user_details->id])}}">{{tr('view_meetings')}}</a>

                                        </div>

                                    </div>

                                </div>

                            </td>

                        </tr>

                        @endforeach
                    </tbody>

                </table>

                <div class="float-right" id="paglink">{{ $users->appends(request()->input())->links() }}</div>

            </div>

        </div>

    </div>

</div>




@endsection

@section('scripts')

@if(Session::has('bulk_action'))
<script type="text/javascript">
    $(document).ready(function() {
        localStorage.clear();
    });
</script>
@endif

<script type="text/javascript">
    $(document).ready(function() {
        get_values();

        // Call to Action for Delete || Approve || Decline
        $('.action_list').click(function() {
            var selected_action = $(this).attr('id');
            if (selected_action != undefined) {
                $('#action').val(selected_action);
                if ($("#selected_ids").val() != "") {
                    if (selected_action == 'bulk_delete') {
                        var message = "{{ tr('admin_users_delete_confirmation') }}";
                    } else if (selected_action == 'bulk_approve') {
                        var message = "{{ tr('admin_users_approve_confirmation') }}";
                    } else if (selected_action == 'bulk_decline') {
                        var message = "{{ tr('admin_users_decline_confirmation') }}";
                    }
                    var confirm_action = confirm(message);

                    if (confirm_action == true) {
                        $("#users_form").submit();
                    }
                    // 
                } else {
                    alert('Please select the check box');
                }
            }
        });
        // single check
        var page = $('#page_id').val();
        $('.faChkRnd:checkbox[name=row_check]').on('change', function() {

            var checked_ids = $(':checkbox[name=row_check]:checked').map(function() {
                    return this.id;
                })
                .get();

            localStorage.setItem("user_checked_items" + page, JSON.stringify(checked_ids));

            get_values();

        });
        // select all checkbox
        $("#check_all").on("click", function() {
            if ($("input:checkbox").prop("checked")) {
                $("input:checkbox[name='row_check']").prop("checked", true);
                var checked_ids = $(':checkbox[name=row_check]:checked').map(function() {
                        return this.id;
                    })
                    .get();
                // var page = {!! $users->lastPage() !!};
                console.log("user_checked_items" + page);

                localStorage.setItem("user_checked_items" + page, JSON.stringify(checked_ids));
                get_values();
            } else {
                $("input:checkbox[name='row_check']").prop("checked", false);
                localStorage.removeItem("user_checked_items" + page);
                get_values();
            }

        });

        // Get Id values for selected User
        function get_values() {
            var pageKeys = Object.keys(localStorage).filter(key => key.indexOf('user_checked_items') === 0);
            var values = Array.prototype.concat.apply([], pageKeys.map(key => JSON.parse(localStorage[key])));

            if (values) {
                $('#selected_ids').val(values);
            }

            for (var i = 0; i < values.length; i++) {
                $('#' + values[i]).prop("checked", true);
            }
        }

        $('.faChkRnd').on("click", function() {

            var value = $(this).val();

            $('#check' + value).trigger('click');
        });

    });
</script>

@endsection